[tool.poetry]
name = "backend"        # Can be anything, doesn't have to match a folder
version = "0.1.0"
description = "..."
authors = ["Your Name <you@example.com>"]

# Turn off installing current project
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
spacy = "^3.5.2"
pandas = "^2.0.2"
numpy = "^2.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
